# Generated by Django 3.2.19 on 2023-06-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.IntegerField(null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='keyapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(blank=True)),
                ('desc', models.TextField(max_length=200)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='keyapp.employee')),
            ],
        ),
    ]
