# Generated by Django 3.2.19 on 2023-06-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='desc',
            new_name='shift',
        ),
    ]
